### ISSUE TITLE
Printing problems

### ISSUE THREAD

**Issue by Cr4xy** [tomblind/local-lua-debugger-vscode#14] opened 2020-01-29 08:47 UTC
Printing `{{}}` prints `}}`

This code causes the debugger to stop working/hang:
```
print("{method = \"test\"}")
print("{{}}")
```

**Comment by tomblind** [comment] 2020-02-07 19:27
I can't seem to reproduce this. Can you show me your launch.json config?

**Comment by Cr4xy** [comment] 2020-02-28 13:00
I think it might be because I'm using a logger (http://neopallium.github.io/lualogging/manual.html).
I'm seeing this printed in the console:
```
{
  "threadId": 32,
  "breakType": "breakpoint",
  "tag": "$luaDebug",
  "type": "debugBreak",
  "message": "breakpoint hit: \"...\""
}
```
Here's my launch.json:
```
{
  "name": "Local Lua Debugger",
  "type": "lua-local",
  "request": "launch",
  "cwd": "${workspaceFolder}",
  "program": {
    "lua": "lua5.1",
    "file": "${relativeFile}"
}
...

**Comment by tomblind** [comment] 2020-02-28 15:29
In theory the logger shouldn't conflict with the debugger. I actually managed to reproduce this in one of my own projects the other day. As soon as a get some time, I'll try to debug and fix this.

**Comment by tomblind** [comment] 2020-02-29 16:10
I've just published a new version (0.1.6) which I hope will fix this issue for you. Please let me know if it does (or doesn't).

**Comment by tomblind** [comment] 2020-05-18 14:24
Closing this for now since as far as I know, it's fixed.

**Closed by tomblind** 2020-05-18 14:24 UTC
Labels: bug
